version: '2'
services:
    vpsmanage-app:
        image: vpsmanage
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vpsmanage-mysql:3306/vpsmanage?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vpsmanage-mysql:
        extends:
            file: mysql.yml
            service: vpsmanage-mysql
